[appendix]
== Mobi Datasets
Mobi datasets are used to group and store RDF data into various graphs for enhanced query isolation, data segmentation, and management. The Mobi dataset structure is defined in a custom ontology found in the `com.mobi.dataset.api/src/main/resources/dataset.ttl` file in the source code. This design is loosely based on the https://www.w3.org/TR/rdf-sparql-query/#rdfDataset[W3C Specification for SPARQL Datasets] wherein a collection of graphs can be queried as default named graphs or named graphs. The primary class is `dataset:Dataset`, and the properties associated with this class provide information about all the named graphs within the dataset. These properties are:

* `<<systemDefaultNamedGraph>>`
* `<<defaultNamedGraph>>`
* `<<namedGraph>>`

[NOTE]
====
All examples in this Appendix will be in TriG RDF serialization and use the following prefixes:

[cols="2*",options="header"]
|===
|Prefix
|Namespace

|`example`
|\http://guide.org/

|`dataset`
|\http://mobi.com/ontologies/dataset#

|===
====

=== systemDefaultNamedGraph
The `dataset:systemDefaultNamedGraph` property specifies the default named graph that Mobi will use when loading data that does not specify a graph (e.g. data from a Turtle file). For example, this approach is currently used for data created by the <<mapping-tool-guide,Mapping Tool>>. This named graph will be cleared, but not removed when a dataset is cleared.

.`systemDefaultNamedGraph`
====
[listing%nowrap]
....
GRAPH example:DatasetExample {
    example:DatasetExample a dataset:Dataset ;
        dataset:systemDefaultNamedGraph example:sdng .
}

GRAPH example:sdng {
    example:Subject a example:Object .
}
....
====

=== defaultNamedGraph
The `dataset:defaultNamedGraph` property specifies a default named graph within the dataset. These graphs are not maintained by the system and can be used when data segmentation is required within a dataset. These graphs are removed when a dataset is cleared.

.`defaultNamedGraph`
====
[listing%nowrap]
....
GRAPH example:DatasetExample {
    example:DatasetExample a dataset:Dataset ;
        dataset:defaultNamedGraph example:dng .
}

GRAPH example:dng {
    example:Subject a example:Object .
}
....
====

=== namedGraph
The `dataset:namedGraph` property specifies a named graph within the dataset. These graphs are not maintained by the system and can be used when data segmentation is required within a dataset. These graphs are removed when a dataset is cleared.

.`namedGraph`
====
[listing%nowrap]
....
GRAPH example:DatasetExample {
    example:DatasetExample a dataset:Dataset ;
        dataset:namedGraph example:ng .
}

GRAPH example:ng {
    example:Subject a example:Object .
}
....
====
