[[configuration-guide]]
=== Configuration
All default configuration files for Apache Karaf and Mobi are located inside the `{MOBI_HOME}/etc` directory.

==== Mobi

===== Service Configuration
The basic Mobi services can be configured using the following files:

.Mobi Service Configuration Files
|===
|Configuration File |Description

|`com.mobi.catalog.config.CatalogConfigProvider.cfg`
|Configurations for the Mobi Catalog

|`com.mobi.platform.config.state.StateManager.cfg`
|Configurations for the Mobi State Manager

|`com.mobi.service.repository.native-system.cfg`
|Configurations for the Mobi System Repository

|`com.mobi.service.repository.native-prov.cfg`
|Configurations for the Mobi Provenance Repository
|===

By default, all resources besides provenance data are stored in the system repository which is an RDF triplestore located in the `data/repos/system` directory of the Mobi distribution. The provenance data is stored within the prov repository. Each repository in Mobi is uniquely identified by its id. To change the data location, id, or title of either repository, edit the [underline]#dataDir#, [underline]#id#, and [underline]#title# properties respectively in the appropriate file. Apache Karaf will dynamically reload any changes made to this existing file.

You can create new repositories to be used for storage in Mobi. First, choose either a "native" repository or a "memory" repository. These two types of repositories are defined in the `NativeRepositoryConfig` and `MemoryRepositoryConfig` classes in the `com.mobi.repository.impl.sesame` module. Once you have chosen the type of repository, make a new `.cfg` file in the `{MOBI_HOME}/etc` directory with a file name that starts with either "com.mobi.service.repository.native" or "com.mobi.service.repository.memory". In the file, set the [underline]#id#, [underline]#title#, and [underline]#dataDir# properties you wish for the repository. The file should look like this:

----
id=demo
title=Demonstration
dataDir=path/to/directory
----

Apache Karaf will automatically recognize the new configuration file and create the new repository.

The repository that all Catalog resources are stored with is controlled within the `com.mobi.catalog.config.CatalogConfigProvider.cfg` file. The storage repository for all other types of data are controlled individually in other configuration files. To change each of these repository configurations, open the associated `.cfg` file and change the id of the [underline]#repository.target# property to be the id of the new repository. For example to change the repository for storing Catalog resources to the repository in the example above, you would open the `com.mobi.catalog.config.CatalogConfigProvider.cfg` file and edit the repository target line to be:

----
repository.target = (id=demo)
----

Apache Karaf will automatically detect the changes and reload the new configuration.

===== Security Configuration
The configuration for user authentication, authorization, and management are stored in the following files in the `{MOBI_HOME}/etc` directory:

.Mobi Security Configuration Files
|===
|Configuration File |Description

|`com.mobi.jaas.engines.RdfEngine.cfg`
|Configurations for the Mobi RDF Engine

|`com.mobi.security.policy.api.xacml.XACMLPolicyManager.cfg`
|Configurations for the XACML security policy manager
|===

Mobi utilizes JAAS for user authentication and basic authorization. By default, user credentials and information are managed by the `RdfEngine` service which is configured with the `com.mobi.jaas.engines.RdfEngine.cfg` file. The file contains an id of the repository to be used for storage, the encryption settings for JAAS which are enabled to start, and the two default roles: "user" and "admin". Apache Karaf will automatically detect any changes and reload the updated configurations.

The default user for Mobi is "admin" with password "admin". To change the credentials of the "admin" user or perform any other user management activities, utilize the <<administration-guide,Administration>> page, the <<my-account-guide,My Account>> page, or the appropriate REST endpoints.

For more advanced authorization functionality, Mobi uses the an Attribute Based Access Control (ABAC) system called https://www.oasis-open.org/committees/xacml/[XACML]. Policies describing the attributes for allowing or denying individual access requests are managed by the `XACMLPolicyManager` service which is configured with the `com.mobi.security.policy.api.xacml.XACMLPolicyManager.cfg` file. The file contains an id of the repository to be used for storage, the location the XACML policy files should be stored in, and whether the policy file location should be created if it does not already exist. Apache Karaf will automatically detect any changes and reload the updated configurations.

===== Email Service Configuration
The configuration for the Mobi Email Service is stored in the following file in the `{MOBI_HOME}/etc` directory:

.Mobi Email Service Configuration Files
|===
|Configuration File |Description

|`com.mobi.email.api.EmailService.cfg`
|Configurations for the Mobi Email Service
|===

The Mobi Email Service is built on the Apache Commons Email API. The Email Service provides the ability to connect to a provided SMTP server and send an email using a configured email account. By default, the service is configured to connect to a Gmail SMTP server in the `com.mobi.email.api.EmailService.cfg` file. The service has configurations for `smtpServer`, `port`, `emailAddress`, `emailPassword`, `security`, and `emailTemplate`. Please see below for different configurations of popular email services.

===== Email Template
The Mobi Email Email Service supplies a default email template that works across most email clients. The default file is located in the `{MOBI_HOME}/etc` directory. If you want to provide your own email template, modify the `emailTemplate` configuration to the new email template with either a relative or absolute path to the file. The email service will resolve relative file paths for an email template using the `{MOBI_HOME}/etc` directory as the base directory.

The email service provides a method for doing a simple string replace on the `!|$MESSAGE!|$` binding within the template. For more complex HTML inserts, the service provides a method to replace all HTML between the two `!|$BODY!|$` bindings. Custom templates must have the aforementioned bindings (`!|$MESSAGE!|$` & `!|$BODY!|$`). The `!|$MESSAGE!|$` binding must be between two `!|$BODY!|$` bindings. For example:
```
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
...
<body>
!|$BODY!|$
<table>
    <tbody>
    <tr>
        <td>
            <p>
                <!-- A simple message to replace -->
                !|$MESSAGE!|$
            </p>
        </td>
    </tr>
    </tbody>
</table>
!|$BODY!|$
...
</body>
</html>
```
===== SMTP Configurations
====== Gmail
To send emails with Gmail, you must also follow the steps https://myaccount.google.com/lesssecureapps[here] to allow less secure apps to access the gmail account. Gmail also has https://support.google.com/a/answer/166852[strict sending limits] that can impair functionality as your organization grows. Additionally, Gmail may flag a machine that it does not recognize and prevent access. If this occurs, log in to your gmail and https://myaccount.google.com/device-activity[grant the device access].
....
smtpServer = smtp.gmail.com
emailAddress = my.email@gmail.com
emailPassword = my-password
port = 587
security = STARTTLS
emailTemplate = emailTemplate.html
....
====== Outlook
....
smtpServer = smtp-mail.outlook.com
emailAddress = my.email@outlook.com
emailPassword = my-password
port = 587
security = STARTTLS
emailTemplate = emailTemplate.html
....
====== Office 365
....
smtpServer = smtp.office365.com
emailAddress = my.email@yourdomain.com
emailPassword = my-password
port = 587
security = STARTTLS
emailTemplate = emailTemplate.html
....
====== Yahoo
....
smtpServer = smtp.mail.yahoo.com
emailAddress = my.email@yahoo.com
emailPassword = my-password
port = 465
security = STARTTLS
emailTemplate = emailTemplate.html
....
====== Mailgun
....
smtpServer = smtp.mailgun.org
emailAddress = my.email@mg.gitlab.com
emailPassword = my-password
port = 587
security = STARTTLS
emailTemplate = emailTemplate.html
....

==== Apache Karaf
The Karaf instance that runs Mobi can be configured using the configuration files located in the `{MOBI_HOME}/etc`
 directory.

.Relevant Karaf Configuration Files
|===
|Configuration File |Description

|`org.ops4j.pax.url.mvn.cfg`
|Configurations for Maven repositories used for bundle resolution and deployment

|`org.ops4j.pax.web.cfg`
|Configurations for HTTPS connections
|===

The `org.ops4j.pax.url.mvn.cfg` file specifies how Apache Karaf will resolve Maven URLs. This file is set up so that
Apache Karaf will use the basic Maven repositories along with your local Maven repository and the public Mobi remote
repository to resolve artifacts.

The `org.ops4j.pax.web.cfg` file configures the web service Apache Karaf uses to run Mobi. By default, Mobi only
runs HTTPS on port 8443.
