[[administration-guide]]
== Administration Guide
Mobi is made available as a compressed distribution package available
https://mobi.inovexcorp.com/features/#download[here]. Deployment
consists of unpacking this distribution to an appropriate location on
the filesystem and modifying included configuration files. Mobi comes
pre-bundled with an open-source, file-based RDF database. By default,
all data, logs, and configurations will be stored in the extracted file
location.

=== Mobi Requirements

==== Hardware Requirements

We provide recommended hardware requirements as a guideline. These
specifications are based on standard deployment environments. Larger
production data or user requirements may require more powerful hardware
configurations.

The table below provides a summary of the recommended hardware for
production servers and the minimum requirements for test servers.

[cols=",,,",options="header",]
|===
|*Component* |*Minimum* |*Recommended* |*Guidelines*
|Available RAM |1 GB |8 GB or more |Mobi needs enough RAM to load large
ontology and data files and run Mobi processes. The configurations
provided refer to maximum Java heap size.

|Disk Space |10 GB |40 GB or more |By default, Mobi stores all data and
configurations in the extracted file location.

|CPU |1 core |4 cores or more |Multi-core configurations dramatically
improve performance of the bundled application server and database.
|===

==== Software Requirements

The table below provides a summary of the software requirements.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Component* |*Minimum* |*Recommended* |*Guidelines*
|Operating System |RHEL/CentOS 6 +
Windows 7 +
OSX |RHEL/CentOS 8 |Mobi runs within standard Java runtimes; however, we
recommend RHEL/CentOS operating systems for on-premise or cloud-based
server environments.

|Java |1.17 |1.17 (latest) |The latest versions of Java 17 include security
and performance updates.

|Web Browser |Chrome +
Firefox +
Safari +
Edge |Chrome |Use the latest versions of web browsers for best
compatibility, performance, and security.
|===

==== Firewall Requirements

The table below lists the TCP ports to open on the Mobi host.

[cols=",",options="header",]
|===
|*Port* |*Description*
|8443 |Application HTTPS port.
|===

TIP: We recommend running Mobi on the default port 8443 and using firewall
configuration or a proxy server for SSL (port 443) termination and
redirection. Mobi does not run on non-SSL ports by default.

=== Installing Mobi

==== Pre-Installation Configuration

===== Create Service Account

Before installing Mobi, create a service account on the host server. The
account will be used to run Mobi. The service account should meet the
following requirements:

* The service account must have read and write permissions for the Mobi
installation directory. On Linux, this is typically
`/opt/mobi/mobi-distribution-<version>`.

On a standard RHEL/CentOS system, this can be created using the
following command:

[source,bash]
----
sudo useradd -d /opt/mobi mobi
----

===== Install Java 17

Mobi requires the latest version of Java 1.17 to operate. On a standard RHEL/CentOS system, there is no package available via `yum` to install. So we suggest Downloading the Oracle installer from https://www.oracle.com/java/technologies/downloads/#java17[here] and running it manually using the following commands:

[source,bash]
----
wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm 
sudo rpm -Uvh jdk-17_linux-x64_bin.rpm 
----

NOTE: If you are using a Red Hat system, you can install Java 17 with `sudo yum install java-17-openjdk`

The `JAVA_HOME` environment variable must be set for the user running Mobi. On a standard RHEL/CentOS system (after running the rpm above) this can be set using the following commands:

[source,bash]
----
sudo su - mobi
echo 'export JAVA_HOME=/usr/java/jdk-17.0.4.1' >> ~/.bashrc
exit
----

==== Install Mobi

Follow the instructions below to install Mobi. These instructions assume
that you have copied the Mobi distribution to the server.

NOTE: These instructions are prepared for a standard RHEL/CentOS deployment
server.

. Unpack Mobi to the installation parent directory (e.g. */opt/mobi*)
+
[source,bash]
----
sudo su - mobi
tar -xf $MOBI_DIST.tar.gz
----

. Create a symlink to the latest distribution
+
[source,bash]
----
ln -s $MOBI_DIST latest
----

. Start the Mobi server
+
[source,bash]
----
cd latest
./bin/start
----

To stop the Mobi server, run the following command:

[source,bash]
----
./bin/stop
----

==== Post-Installation Configuration

===== Change the Default Java Heap Size

Set the max heap size in `$MOBI_DIST/bin/setenv` (e.g.
`JAVA_MAX_MEM=4G`). In version 1.21, to include the `JAVA_MAX_MEM` and `JAVA_MIN_MEM` variables in the Mobi startup, add the following line beneath them in the `setenv` file. 

NOTE: All versions from 1.22 onwards have this line already added.

[source,bash]
----
export JAVA_OPTS="-Xms${JAVA_MIN_MEM} -Xmx${JAVA_MAX_MEM}"
----

===== Change the Default Web Port

Change the default SSL port in `$MOBI_DIST/etc/org.ops4j.pax.web.cfg`

[source,bash]
----
org.osgi.service.http.port.secure = <SSL_APPLICATION_PORT>
----

TIP: We recommend running Mobi on the default port 8443 and using firewall
configuration or a proxy server for SSL (port 443) termination and
redirection. Mobi does not run on non-SSL ports by default.

===== Configure Custom SSL Certificates

Mobi comes bundled with default self-signed SSL certificates stored in a
https://www.sslshopper.com/article-most-common-java-keytool-keystore-commands.html[Java
Keystore] file in `etc/keystore`. To provide your own SSL certificates,
simply replace the default keystore file with your own:

[source,bash]
----
cp mycerts.jks $MOBI_DIST/etc/keystore
----

If there is a keystore password, it can be configured in the
`$MOBI_DIST/etc/org.ops4j.pax.web.cfg` file using the following
configuration properties:

[cols=",",options="header",]
|===
|*Configuration Property* |*Description*
|*org.ops4j.pax.web.ssl.keystore.password* |The password used for keystore
integrity check

|*org.ops4j.pax.web.ssl.key.password* |The password used for keystore
|===

===== Installing Mobi as a Service

We recommend that you configure Mobi as a Linux service for starting
Mobi automatically as the service user. Follow the instructions below to
implement the service on a standard RHEL/CentOS environment.

NOTE: The below steps should be run as the root user.

WARNING: Be sure to correctly configure the file locations and user.

. Create a file called *mobi.service* in the `/usr/lib/systemd/system`
directory. For example:
+
[source,bash]
----
[Unit]
Description=Mobi Service.
After=network.target
StartLimitIntervalSec=30
 
[Service]
Type=forking
PIDFile=/install_path/latest/karaf.pid
User=mobi
ExecStart=/install_path/latest/bin/start
ExecStop=/install_path/latest/bin/stop
ExecReload=/install_path/latest/bin/stop; /install_path/latest/bin/start
Restart=always
 
[Install]
WantedBy=default.target
----
. Save and close the file, and then run the following commands to start
and enable the new service:
+
[source,bash]
----
systemctl start mobi
systemctl enable mobi
----

Once the service is enabled, Mobi should be running. The Mobi process
will start and stop automatically with the server. Any time you start
and stop Mobi manually, run the following systemctl commands:
`sudo systemctl stop mobi` and `sudo systemctl start mobi`.

===== Configure Default Authentication Token (JWT) Duration

To configure the web authentication token duration, you
must create a file called `com.mobi.jaas.SimpleTokenManager.cfg` with
the property detailed below and put it in the `etc/` directory of your
Mobi installation before starting the application, otherwise the token
duration will use the default of 24 hours.

NOTE: In Enterprise deployments, this is only applied to non-SSO based authentication.

[cols=",,,",options="header",]
|===
|*Property Name* |*Description* |*Required* |*Default*
|tokenDurationMins |Token Duration time in minutes | |1440
|===

An example file would look like this.

[source,bash]
----
### 1 day token duration
tokenDurationMins = 1440
----

NOTE: .p12 and .jks files should both be supported

===== LDAP Configuration (ENTERPRISE)

In Enterprise deployments only, Mobi can be configured so that users can log into the application with the Users/Groups defined
in your organization's directory, you must create a file called
`com.mobi.enterprise.ldap.impl.engine.LDAPEngine.cfg` with the following
properties and put it in the `$MOBI_DIST/etc/` directory before starting
the application. If a property is not required, you can delete the line
from the config file. The list of possible fields for the config file
are shown in the table below.

[cols=",,,",options="header",]
|===
|*Property Name* |*Description* |*Required* |*Default*
|repository.target |Should always be (id=system)
|Yes |

|ldap.server |The hostname of the ldap server (ex: localhost)
|Yes |

|ldap.port |The port of the LDAP server (ex: `10389`)
|Yes |

|ldap.timeout |The number of seconds it will keep trying to reach the
LDAP server before it gives up (ex: `30`)
|Yes |30

|ldap.ssl |Whether to connect to the LDAP engine with SSL (ex: false) |
|false

|ldap.disable-auth |Whether direct authentication to the LDAP engine is
disabled (ex: `false`) | |false

|ldap.expiry |The number of milliseconds before a LDAPUser should be
retrieved (ex: `3600000`) | |3600000

|ldap.admin.dn |The admin DN on your LDAP server (ex:
`uid=admin,ou=system`) | |

|ldap.admin.password |The admin password on your LDAP server (ex:
`secret`) | |

|ldap.users.base |The base DN at which to start looking for users on the
LDAP server (`ex: ou=people,dc=example,dc=com`)
|Yes |

|ldap.users.filter |An optional LDAP filter for retrieved users. (ex:
`(businessCategory=Managers)` ) | |

|ldap.users.id |The field name on users that the Mobi
application will use as the username to log in (ex: `uid`)
|Yes |

|ldap.users.firstName |The field name on users whose value is the first
name of the user (ex: `givenName`) | |

|ldap.users.lastName |The field name on users whose value is the last
name of the user (ex: `sn`) | |

|ldap.users.email |The field name on users whose value is the email
address of the user (ex: `mail`) | |

|ldap.users.membership |The field name on users whose values are the
groups they are a part of (ex: `memberOf`)
|Yes |

|ldap.users.membership.search |The format of the user membership field.
Should be set to the field name on groups that the values of the user
membership field uses. If this is not set, assume the values are full
group DNs. (ex: `cn`) | |

|ldap.groups.base |The base DN at which to start looking for groups on
the LDAP server (ex: `ou=groups,dc=example,dc=com`)
|Yes |

|ldap.groups.filter |An optional LDAP filter for retrieved groups (ex:
`(businessCategory=Managers)` ) | |

|ldap.groups.id |The field name for groups' ids (ex: `dn`)
|Yes |

|ldap.groups.name |The field name for groups' names/titles (ex: `title`)
| |

|ldap.groups.description |The field name on groups whose value is the
description of the group (ex: `description`) | |

|ldap.groups.membership |The field name on groups whose values are the
users that are a part of the group (ex: `member`)
|Yes |

|ldap.groups.membership.search |The format of the group membership
field. Should be set to the field name on users that the values of the
group membership field uses. If this is not set, assume the values are
full user DNs. (ex: `uid`) | |
|===

An example file would look like this.

[source,bash]
----
repository.target = (id=system)
ldap.server = localhost
ldap.port = 10389
ldap.timeout = 30
ldap.admin.dn = uid=admin,ou=system
ldap.admin.password = secret
ldap.users.base = ou=people,dc=example,dc=com
ldap.users.filter = (businessCategory=Superhero)
ldap.users.id = uid
ldap.users.firstName = givenName
ldap.users.lastName = sn
ldap.users.membership = memberOf
ldap.groups.base = ou=groups,dc=example,dc=com
ldap.groups.id = cn
ldap.groups.name = cn
ldap.groups.description = description
ldap.groups.membership = member
----

===== SSO Configuration (ENTERPRISE)

In Enterprise deployments only, Mobi can be configured to integrate with an SSO provider for authentication. LDAP can be configured alongside the SSO provider to retrieve additional user details, but it is not required. If configured, it is recommended to disable direct authentication against the LDAP directory by adding `ldap.disable-auth = false` to the `com.mobi.enterprise.ldap.impl.engine.LDAPEngine.cfg` file. Mobi supports SAML, OAuth 2.0, and OpenID SSO providers.

====== SAML Configuration

In order to configure Mobi to use SAML, you will need to create a file
called `com.mobi.enterprise.auth.saml.api.SAMLConfigProvider.cfg` to the
`$MOBI_DIST/etc/` directory. The must have the following fields.

NOTE: `${karaf.etc}` is a reference to the `$MOBI_DIST/etc/` directory that the
application will understand and replace

NOTE: In order for the `certFile` to ba valid format, it must contain the appropriate `-----BEGIN CERTIFICATE-----` header and `-----END CERTIFICATE-----` footer

[cols=",,",options="header",]
|===
|*Property Name* |*Description* |*Required*
|title 
|The title for the SSO provider. This title will be used in the UI for triggering the SSO authentication in the format of “Login with _title”_ 
|Yes

|entityId 
|The SP EntityId. The SSO provider must be configured to expect requests with this SP EntityId
|Yes

|certFile 
|The file path to a file containing the X509 certificate for verifying the signature of SAML responses. Best practice is to put the file in the `$MOBI_DIST/etc/` directory and make this value `${karaf.etc}/<INSERT-FILE-NAME>`
|Yes

|keyFile 
|The optional file path to a file containing the PKCS8 key for verifying the signature of SAML responses. Best practice is to put the
file in the `$MOBI_DIST/etc/` directory and make this value `${karaf.etc}/<INSERT-FILE-NAME>` 
|

|ssoUrl 
|The URL for the SingleSignOnService from the IdP. This is where Mobi will redirect to.
|Yes

|idAttribute 
|The name of the `Attribute` in the SAML response where the username can be found. Defaults to using the `<UserId>`. 
|

|ssoBinding 
|The full URN of the binding to be used for the SAML Requests. Defaults to `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect` 
|

|standalone 
|Whether the SAML configuration should be considered by itself or with a LDAP backend as well. Defaults to `false`. If `true`, the properties below are applied.
|

|firstNameAttribute
|An optional property to specify the name of the attribute in the SAML responses that contains the first name of the authenticated user. Only applicable if `standalone`.
|

|lastNameAttribute
|An optional property to specify the name of the attribute in the SAML responses that contains the last name of the authenticated user. Only applicable if `standalone`.
|

|emailAttribute
|An optional property to specify the name of the attribute in the SAML responses that contains the email of the authenticated user. Only applicable if `standalone`.
|

|groupAttribute
|An optional property to specify the name of the attribute in the SAML responses that contains the groups that the authenticated user is a part of. The values of this attribute will be used as the Group's title in Mobi. Only applicable if `standalone`.
|
|===

An example file with an LDAP backend would look like this.

[source,bash]
----
title=Samling
entityId=https://localhost:8443/mobi/#/login
certFile=${karaf.etc}/samling.cert
keyFile=${karaf.etc}/samling_pkcs8.key
ssoUrl=https://capriza.github.io/samling/samling.html
idAttribute=ShortName
ssoBinding=urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
----

An example `standalone` configuration would look like this.

[source,bash]
----
title=Samling
entityId=https://localhost:8443/mobi/#/login
certFile=${karaf.etc}/samling.cert
keyFile=${karaf.etc}/samling_pkcs8.key
ssoUrl=https://capriza.github.io/samling/samling.html
idAttribute=ShortName
ssoBinding=urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
standalone=true
firstNameAttribute=FirstName
lastNameAttribute=LastName
emailAttribute=MBox
groupAttribute=Groups
----

====== Default SAML Token Duration

In order to configure the token duration for SAML logins, you must
create a file called `com.mobi.enterprise.auth.rest.SAMLRest.cfg` with
the following properties and put it in the `$MOBI_DIST/etc/` directory
before starting the application, otherwise the token duration will use
the default of one day. There is only one possible field for the config
file as shown in the table below that is configurable and not required
to set the token duration value.

[cols=",,,",options="header",]
|===
|*Property Name* |*Description* |*Required* |*Default*
|tokenDurationMins |Token Duration time in minutes | |1440
|===

An example file would look like this.

[source,bash]
----
### 1 day token duration
tokenDurationMins = 1440
----

====== OAuth/OpenID Configuration

In order to configure Mobi to use OAuth or OpenID, you will need to create two files in the `$MOBI_DIST/etc` directory: `com.mobi.enterprise.auth.oauth.api.OAuthConfigProvider.cfg` and `com.mobi.enterprise.auth.oauth.impl.token.OAuthTokenLoginModuleProvider.cfg`. The latter must be an empty file. The former can be used to configure a generic OAuth 2.0 Provider or an OpenID Provider. For either, the file must have the following fields.

[cols=",,",options="header",]
|===
|*Property Name* |*Description* |*Required*
|title 
|The title for the SSO provider. This title will be used in the UI for triggering the SSO authentication in the format of “Login with _title”_ 
|Yes

|clientId 
|The ID for the Mobi installation. The OAuth/OpenID provider must be configured to expect requests with this clientId
|Yes

|scope 
|The OAuth scopes to include in the authentication request 
|Yes

|clientSecret 
|The optional client secret to use in requests to the OAuth/OpenID provider.
|

|userIdentifierClaim 
|An optional property to specify which claim in the returned JWT contains the user's username. These values must match what is configured for the LDAP users id. Defaults to using the `sub` of the JWT
|

|standalone 
|Whether the OAuth/OpenID configuration should be considered by itself or with a LDAP backend as well. Defaults to `false`. If `true`, the property below is applied.
|

|groupClaim 
|An optional property to specify which claim in the returned JWT contains the groups the user is a part of. The values of this attribute will be used as the Group's title in Mobi. Only applicable if `standalone`.
|
|===

For OAuth 2.0, the file must also contain these fields.

[cols=",,",options="header",]
|===
|*Property Name* |*Description* |*Required*
|grantType 
|The OAuth 2.0 grant type to use for authentication. Mobi currently supports the CODE and IMPLICIT flows.
|Yes

|redirectUrl 
|The URL for the OAuth/OpenID provider. This is where Mobi will redirect to.
|Yes

|tokenUrl 
|The URL to hit to retrieve the token in the CODE flow.
|

|keyFile 
|The file path to a file containing the PKCS8 key for verifying the signature of JWT tokens. Best practice is to put the file in the `$MOBI_DIST/etc/` directory and make this value `${karaf.etc}/<INSERT-FILE-NAME>`
|Yes
|===

An example file would look like this.

[source,bash]
----
title=Mock OAuth
clientId=mobi
scope=read,openid
grantType=CODE
redirectUrl=http://localhost:8080/authorize
tokenUrl=http://localhost:8080/token
keyFile=${karaf.etc}/NTs4oGbx1A-cROpjgUKdKtzTEkHUhhSwQ7xdhN6FdlQ_pub.pem
----

For OpenID, the file must also contain these fields.

[cols=",,",options="header",]
|===
|*Property Name* |*Description* |*Required*
|openidConfigHostname 
|The hostname of the OpenID provider. The standard `/.well-known/openid-configuration` path will be appended to this value.
|Yes
|===

An example file would look like this.

[source,bash]
----
title=Mock OAuth
clientId=mobi
scope=read,openid
openidConfigHostname=http://localhost:8080
----

====== Azure AD OpenID Setup

If you want to configure OpenID integration with Azure AD, there are a few extra steps that need to be taken due to the unique structure of the returned JWTs.

The complementary LDAP configuration for an Azure AD OpenID provider must set the `userPrincipalName` as the `ldap.users.id` property in the `com.mobi.enterprise.ldap.impl.engine.LDAPEngine.cfg` as the Azure AD JWTs do not contain the typical `samAccountName` values.

In addition, v2.0 of Azure AD adds an additional field to the header of the JWT after signing it, thus making the signature incapable of being verified by the algorithms returned from the JWKS endpoint. In order to stop Azure AD from adding this additional field, you can add a new custom scope to the App registration. The steps to do this are described in this article (https://medium.com/@abhinavsonkar/making-azure-ad-oidc-compliant-5734b70c43ff) under “Problem 1”.

===== Password Encryption Configuration

Mobi provides a way to automatically encrypt plaintext passwords stored
within service configurations on startup and subsequent updates. The setup
for this is very short. All you have to do is ensure that a file called
`com.mobi.security.api.EncryptionService.cfg` exists in the `$MOBI_DIST/etc`
directory and contains the following fields:
[source,bash]
----
enabled=true
password=ENTER_A_UNIQUE_PASSWORD_HERE 
----
NOTE: This password is not the password you want to encrypt, rather it is a unique master
password used for encrypt and decrypt operations.

This encryption config is present and enabled by default, meaning your passwords will be automatically encrypted.
An alternate way of providing an encryption master password is via environment variable.
To configure the use of an environment variable, use the following fields:
[source,bash]
----
enabled=true
variable=MY_CHOSEN_ENVIRONMENT_VARIABLE
----
If you use an environment variable, make sure before you start Mobi that you have stored a
unique password as the value for that environment variable.

WARNING: If there is a default password in the Encryption Config (i.e. `CHANGEME`) make sure
you change it to a unique password before starting Mobi, otherwise your passwords will be easy
to decrypt.

Once the encryption config is added, start Mobi and if a Mobi service configuration includes
a plaintext password, it will encrypt the value and update the configuration file. To
change an encrypted value, simply replace it with the new plaintext value in the
configuration file and after a few seconds it will be automatically re-encrypted and the
file will be updated.

====== Services that use Encryption

[cols=",,",options="header",]
|===
|*Service* |*Config File* |*Field that gets encrypted*
|Email | com.mobi.email.api.EmailService.cfg
|emailPassword
|===

To update the encryption master password, change the password field in the `com.mobi.security.api.EncryptionService.cfg` file while Mobi is running. After a few seconds have passed, all passwords will be automatically re-encrypted using the new master password.

NOTE: If the master password is changed while Mobi is not running, all previously encrypted passwords must be re-entered in plain text for the encryption service to re-encrypt.