[appendix]
== Mobi Mappings
Mobi mappings are used to convert delimited data into RDF and are made up of instances of classes defined in a custom ontology found in the `com.mobi.etl.api/src/main/resources/delimited.ttl` file in the source code. These main classes are:

* `<<Mapping>>`
* `<<ClassMapping>>`
* `<<DataMapping>>`
* `<<ObjectMapping>>`

[NOTE]
====
All examples in this Appendix will be in Turtle RDF serialization and use the following prefixes:

[cols="2*",options="header"]
|===
|Prefix
|Namespace

|`example`
|\http://guide.org/

|`delim`
|\http://mobi.com/ontologies/delimited#

|===
====

=== Mapping
The `delim:Mapping` class represents the mapping itself. Every mapping must have one and only one instance of the `Mapping` class. Properties associated with this class provide information about the mapping that are needed for the <<mapping-tool-guide,Mapping Tool>> to have context. These properties are:

* `<<sourceRecord>>`
* `<<sourceBranch>>`
* `<<sourceCommit>>`

==== sourceRecord
The `delim:sourceRecord` property specifies the `OntologyRecord` a mapping uses for its classes and properties. The <<mapping-tool-guide,Mapping Tool>> requires this property along with `<<sourceBranch>>` and `<<sourceCommit>>` to retrieve a specific version of an ontology saved in Mobi. A mapping will have access to all entities defined in ontologies within the imports closure of the source ontology. The Mapping Tool utilizes all class and property definitions to validate the class and property mappings and apply the correct datatypes to data property values.

.`sourceRecord`
====
[listing%nowrap]
....
example:DocumentExample delim:sourceRecord <http://mobi.com/records/uhtc> .
....
====

==== sourceBranch
The `delim:sourceBranch` property specifies the `Branch` of the `<<sourceRecord>>` a mapping uses for its classes and properties. The <<mapping-tool-guide,Mapping Tool>> requires this property along with `<<sourceRecord>>` and `<<sourceCommit>>` to retrieve a specific version of an ontology saved in Mobi. A mapping will have access to all entities defined in ontologies within the imports closure of the source ontology. The Mapping Tool utilizes all class and property definitions to validate the class and property mappings and apply the correct datatypes to data property values.

.`sourceBranch`
====
[listing%nowrap]
....
example:DocumentExample delim:sourceBranch <http://mobi.com/branches/master> .
....
====

==== sourceCommit
The `delim:sourceCommit` property specifies the `Commit` of the `<<sourceBranch>>` a mapping uses for its classes and properties. The <<mapping-tool-guide,Mapping Tool>> requires this property along with `<<sourceRecord>>` and `<<sourceBranch>>` to retrieve a specific version of an ontology saved in Mobi. A mapping will have access to all entities defined in ontologies within the imports closure of the source ontology. The Mapping Tool utilizes all class and property definitions to validate the class and property mappings and apply the correct datatypes to data property values.

.`sourceCommit`
====
[listing%nowrap]
....
example:DocumentExample delim:sourceCommit <http://mobi.com/commits/0> .
....
====

=== ClassMapping
The `delim:ClassMapping` class represents a blueprint for creating an instance of a class. Every `ClassMapping` defined in a mapping will create an instance of the class it maps to for every row in a set of delimited data. Each class instance created will have a generated IRI. Properties associated with this class specify how the class instance it creates should be constructed. These properties are:

* `<<mapsTo>>`
* `<<dataProperty>>`
* `<<objectProperty>>`
* `<<hasPrefix>>`
* `<<localName>>`

==== mapsTo
The `delim:mapsTo` property specifies the class a `ClassMapping` will create. This is a required property for a `ClassMapping` since otherwise, the <<mapping-tool-guide,Mapping Tool>> will not know which class to create an instance of. It must point to a class that is defined either within the source ontology of the mapping or one of the ontologies in the source ontology's imports closure.

.`mapsTo`
====
[listing%nowrap]
....
example:ClassMappingExample delim:mapsTo <http://mobi.com/ontologies/uhtc> .
....
====

==== dataProperty
The `delim:dataProperty` property specifies a `<<DataMapping>>` that is associated with a `ClassMapping`. It must point to a `<<DataMapping>>` instance defined within the mapping. A `ClassMapping` can have one or more of this property. Every instance of a class created from a `ClassMapping` will have the property specified in the `<<DataMapping>>` specified by `dataProperty`.

.`dataProperty`
====
[listing%nowrap]
....
example:ClassMappingExample delim:dataProperty example:DataMapping1 ;
    delim:dataProperty example:DataMapping2 .
....
====

==== objectProperty
The `delim:objectProperty` property specifies an `<<ObjectMapping>>` that is associated with a `ClassMapping`. It must point to a `<<ObjectMapping>>` instance defined within the mapping. A `ClassMapping` can have one or more of this property. Every instance of a class created from a `ClassMapping` will have the property specified in the `<<ObjectMapping>>` specified by `objectProperty`.

.`objectProperty`
====
[listing%nowrap]
....
example:ClassMappingExample delim:objectProperty example:ObjectMapping1 ;
    delim:objectProperty example:ObjectMapping2 .
....
====

==== hasPrefix
The `delim:hasPrefix` property specifies the namespace of the IRI for every class instance created by a `ClassMapping`. This property is required by the <<mapping-tool-guide,Mapping Tool>> so it knows how to construct the IRI for each class instance created by the `ClassMapping`. The value of this property is a string and must be a valid namespace.

.`hasPrefix`
====
[listing%nowrap]
....
example:ClassMappingExample delim:hasPrefix "http://guide.org/example/" .
....
====

==== localName
The `delim:localName` property specifies how the local name of the IRI will be generated for every class instance created by a `ClassMapping`. This property points to a string literal and must be in the following format. The string must start with a dollar sign ($) and contain either the string "UUID" or a number surrounded by curly braces "{}". The "UUID" string will generate a unique identifier for every class instance created by the `ClassMapping`. A number will grab the value of the column at that zero-based index in the row being mapped. If the column specified has duplicate values, the <<mapping-tool-guide,Mapping Tool>> will combine the properties of every class instance with that IRI and combine them into a single instance. If this property is not set on a `ClassMapping`, the <<mapping-tool-guide,Mapping Tool>> will default to generating a UUID for every class instance.

.`localName`
====
This means every class instance will have a unique identifier for a local name.
[listing%nowrap]
....
example:ClassMappingExample1 delim:localName "${UUID}" .
....

This means every class instance will have the value from the third column for a local name.
[listing%nowrap]
....
example:ClassMappingExample2 delim:localName "${2}" .
....
====

=== DataMapping
The `delim:DataMapping` class represents a blueprint for creating a data property on a class instance. Since data properties in an ontology point to literal values, a `DataMapping` specifies a column whose value in the row being mapped will be used as the value of the generated data property. Properties associated with this class define how a data property will be created. These properties are:

* `<<columnIndex>>`
* `<<data-hasProperty>>`
* `<<datatypeSpec>>`
* `<<languageSpec>>`

==== columnIndex
The `delim:columnIndex` property specifies which column a `DataMapping` should pull the value from to set as the value of the generated data property. This property is required for a `DataMapping` so that the <<mapping-tool-guide,Mapping Tool>> knows where to get the value of a data property. All column values retrieved by this property are interpreted as strings. The value of this property must be a string and all the column indexes are zero-based.

.`columnIndex`
====
This will retrieve the value from the first column.
[listing%nowrap]
....
example:DataMapping1 delim:columnIndex "0" .
....
====

[[data-hasProperty]]
==== hasProperty
The `delim:hasProperty` property specifies which data property a `DataMapping` will create. This property is required for a `DataMapping` so that the <<mapping-tool-guide,Mapping Tool>> knows what property to create. It must point to a data property defined either within the source ontology of the mapping or one of the ontologies in the source ontology's imports closure. This property can be associated with either a `DataMapping` or a `<<ObjectMapping>>`.

.`hasProperty` for `DataMapping`
====
[listing%nowrap]
....
example:DataMapping1 delim:hasProperty <http://mobi.com/ontologies/uhtc/aDataProperty> .
....
====

==== datatypeSpec
The `delim:datatypeSpec` property specifies a manual override for the datatype of generated data property values resulting from a `DataMapping`. By default, the datatype will be determined from the range of the property if found with a fallback of string. This setting has precedence over the range of the property. This property is optional for a `DataMapping`. The value of this property must be the IRI of a standard XSD datatype.

.`datatypeSpec`
====
This will set the datatype of all values to xsd:double.
[listing%nowrap]
....
example:DataMapping1 delim:datatypeSpec xsd:double .
....
====

==== languageSpec
The `delim:languageSpec` property specifies a language for all generated data property values resulting from a `DataMapping`. If this property is set, the mapper will manually change the datatype of the value to be `rdfs:langString`. Any datatype specified by the range of the property will be ignored. This property is optional for a `DataMapping`. The value of this property must be a valid language tag string (found https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes[here] under the ISO 639-1 column).

.`languageSpec`
====
This will set the language of all values to be English.
[listing%nowrap]
....
example:DataMapping1 delim:languageSpec "en" .
....
====

=== ObjectMapping
The `delim:ObjectMapping` class represents a blueprint for creating an object property on a class instance. Since object properties in an ontology point to other classes or class expressions, an `ObjectMapping` specifies a `ClassMapping` that will be created for the same row and whose generated class instance will be used as the value of the generated object property. Properties associated with this class define how an object property will be created. These properties are:

* `<<classMapping>>`
* `<<object-hasProperty>>`

==== classMapping
The `delim:classMapping` property specifies which class instance generated from a `ClassMapping` will be used as the value of the generated object property. This property is required for an `ObjectMapping` so that the <<mapping-tool-guide,Mapping Tool>> knows which class should be the value of the object property. The generated value will be the class instance created by the specified `ClassMapping` for the row being mapped. The value must be a `ClassMapping` defined within the mapping.

.`classMapping`
====
[listing%nowrap]
....
example:ObjectMapping1 delim:classMapping delim:ClassMappingExample .
....
====


[[object-hasProperty]]
==== hasProperty
The `delim:hasProperty` property specifies which object property an `ObjectMapping` will create. This property is required for an `ObjectMapping` so that the <<mapping-tool-guide,Mapping Tool>> knows what property to create. It must point to a object property defined either within the source ontology of the mapping or one of the ontologies in the source ontology's imports closure. This property can be associated with either a `ObjectMapping` or a `<<DataMapping>>`.

.`hasProperty` for `ObjectMapping`
====
[listing%nowrap]
....
example:ObjectMapping1 delim:hasProperty <http://mobi.com/ontologies/uhtc/aObjectProperty> .
....
====
