= Mobi Release Notes
:toc: left
:toclevels: 3
:linkcss:
:experimental:
:idprefix:
:source-highlighter: highlight.js
:highlightjsdir: ../highlight
:favicon: ../favicon.ico
:docinfodir: ../

Mobi is an open and collaborative knowledge graph platform for teams and communities to publish and discover data, data models, and analytics that are instantly consumable. These are the Release notes for the Mobi platform.

== Release Notes for Mobi 2.1
Mobi 2.1 released on December 16, 2022. This release includes more intuitive changes displays, multiple improvements for "solutioneers" building on top of Mobi, and a variety of performance enhancements and bug fixes.

=== What's New
* We've updated all displays of changed triples to be consistently formatted and introduced a new toggle to display all unchanged triples as well, enabling more context when reviewing
* We've moved all default policies and policy templates to a specific location in the installation directory so administrators can customize the default permissions for their Mobi instance

=== Detailed Notes

==== General Improvements and Fixes
* Upgraded RDF4J to 4.2.1
* Upgraded Karaf to 4.4.2
* Created a folder in the installation directory to hold all policy templates used for new records and the default system policies (See link:/latest/index.html#mobi_security_policies[Mobi Security Policies])
* Added a new command to the Mobi Karaf shell that will revert all system policies to the defaults specified in the new directory (See <<Mobi Security Policies>>)
* Enabled ability to reach the Swagger Documentation without specifying `/index.html` at the end of the URL
* (ENTERPRISE) Added ability to provide a custom relay state on SAML redirects to support custom solutions in the platform to use the Mobi SSO connectivity

==== Catalog
* Updated all triple changes displays to display triples grouped by property and delineated with `++` and `--` symbols
* Added "Show Full" toggle to all changes displays except in the Commit Information modal which will display all triples for a particular subject alongside the changed triples

==== Ontology Editor
* Updated all triple changes displays to display triples grouped by property and delineated with `++` and `--` symbols
* Added "Show Full" toggle to all changes displays except in the Commit Information modal which will display all triples for a particular subject alongside the changed triples
* Added logic to clean up user state associated with a deleted record
* Added success toast on commit
* Improved performance of hierarchy renders on first load
* Fixed issue where updates to an IRI used in a complex restriction were not reflected

==== Link (ENTERPRISE)
* Fixed issue where results were not shown for a new analysis if the previous analysis results were empty

==== Merge Requests
* Updated all triple changes displays to display triples grouped by property and delineated with `++` and `--` symbols
* Added "Show Full" toggle to all changes displays except in the Commit Information modal which will display all triples for a particular subject alongside the changed triples

==== Shapes Editor
* Updated all triple changes displays to display triples grouped by property and delineated with `++` and `--` symbols
* Added "Show Full" toggle to all changes displays except in the Commit Information modal which will display all triples for a particular subject alongside the changed triples
* Added logic to clean up user state associated with a deleted record
* Added success toast on commit

==== Mapping Tool
* Updated all triple changes displays to display triples grouped by property and delineated with `++` and `--` symbols
* Added "Show Full" toggle to all changes displays except in the Commit Information modal which will display all triples for a particular subject alongside the changed triples

==== Datasets
* Introduced restrictions on uploads to datasets to protect system graphs

==== Administration
* Changed the Permissions page to dynamically pull the list of system policies allowing new policies introduced to automatically appear in the list
* Fixed issue where deleting a group referenced in a policy would not allow that policy to be edited

=== Hotfixes

==== Version 2.1.1
Hotfix 2.1.1 was released on December 19, 2022.

* Reverted the Karaf version to 4.4.1 due to a bug with the `bin/client` script

== Release Notes for Mobi 2.0
Mobi 2.0 released on September 15, 2022. This major release includes major infrastructure updates throughout the platform along with a variety of performance enhancements and bug fixes. Most impactful changes are a new requirement for Java 17 and the entire web application is now built with Angular 6 and more consistent of an experience.

NOTE: For those upgrading from 1.x to 2.0, follow our https://inovexirad.atlassian.net/servicedesk/customer/kb/view/2588246017[Migration Guide]

=== What's New
* We've upgraded our Karaf, Angular, RDF4J, and OSGi dependencies to take advantage of the latest stability and functionality improvements
* We've updated the required Java version to 17

WARNING: Mobi will now no longer start the Java version is older than 17. Please ensure your Java version is correct and the `$JAVA_HOME` environment is set properly as described in <<Administration Guide>>.

WARNING: With the latest version of Karaf, the password properties in `$MOBI_HOME/etc/org.ops4j.pax.web.cfg` that enable custom SSL certificates have changed. See <<Configure Custom SSL Certificates>>.

=== Detailed Notes

==== General Improvements and Fixes
* Upgraded Karaf to 4.4.1
* Upgraded Angular to 6.1.10 and removed all usages and references to AngularJS
* Upgraded RDF4J to 4.1.0
* Upgraded OSGi to 8
* Updated the required Java version to 17
* Updated the required NodeJS version for building the source to 14+
* Updated the required Maven version for building the source to 3.6+
* Replaced `osgi-jax-rs-connector` with Apache Aries Whiteboard Extender for all REST services
* Removed all Mobi API wrappers around RDF4J and switched to using the library directly for drastic performance improvements
* Removed the OWL API based implementation of our Ontology API 

==== Ontology Editor
* Fixed issue where blank nodes would be detached on upload changes if the IRI of the parent node changed
* Fixed issue where blank node IDs with hyphens would be affected when previewing the ontology data

==== Discover
* Removed the outdated and underutilized Search tab

=== Hotfixes

==== Version 2.0.3
Hotfix 2.0.3 was released on November 16, 2022.

* Fixed an issue where clicking on a search result in the Ontology Editor Search tab did not bring up a display of the entity
* Fixed an issue where the Ontology Editor would bring users to the Visualization tab after uploading changes instead of the Changes tab
* Fixed an issue where the page index of the list of Changes in the Ontology Editor and Shapes Editor did not reset when the changes were removed

==== Version 2.0.2
Hotfix 2.0.2 was released on November 2, 2022.

* (ENTERPRISE) Fixed issue where certain screens with a lot of content were not scrolling properly
* Fixed issue where final blank nodes in RDF Lists were left dangling on delete and were not rendered properly in changes displays
* Fixed issue where the btn:[Load More] buttons in the Ontology Editor and Shapes Editor merge previews did not render more content
* Fixed issue where failed upload changes processes in the Ontology Editor did not display any error messages
* Fixed issue where Mobi would not build or run on ARM based Machines
* Fixed issue where ontologies with mid to large size class hierarchies took a long time to open
* Fixed issue where IRIs of entities being created in the Ontology Editor could not be edited before being saved
* Fixed issue where the Schemes and Concepts tabs did not render immediately after SKOS was added to the imports closure

==== Version 2.0.1
Hotfix 2.0.1 was released on October 16, 2022.

* Fixed issue where Merge Requests could not be accepted

== Release Notes for Mobi 1.22
Mobi 1.22 released on June 22, 2022. This release includes extensive application of Dataset policies throughout the platform, full policy management in the Catalog, enhanced access control on Shapes Graph Records, and a prepackaged default trust store for secure SSL communications. It also includes various bug fixes and improvements.

=== What's New
* We've consolidated access control management of all records into the Catalog
* We've included a default trust store with the platform to simplify the process to enable secure SSL communication with external sources
* We've introduced a new policy for controlling who can create Shapes Graph Records

WARNING: All system level policies will be reset to their defaults on a restore into this version and will need to be updated to the desired state again.

=== Detailed Notes

==== General Improvements and Fixes
* Introduced a new bundled trust store that is used throughout the platform when establishing connections to outside sources, including importing ontologies from the web
* Adjusted the `setenv` file to make setting the max and min memory usage more straightforward
* Fixed issue where un-encrypted configuration properties would be encrypted on restore even if auto-encryption was not enabled

==== Catalog
* Introduced new UI for editing the policy of any Record in the platform to centralize and simplify the functionality

==== Ontology Editor
* Removed the UI for managing ontology access in favor of the new consolidated experience in the Catalog
* Updated the backend SPARQL endpoints for querying ontologies to more closely align with the SPARQL 1.1 W3C specification and behave similarly to the overall SPARQL endpoint used for querying datasets and repositories
* Fixed issue where merges could be submitted even when there were no commits different between the source and target branches
* Fixed issue where entities with empty label values would prevent the ontology from being opened

==== Merge Requests
* Fixed issue where merges could be submitted even when there were no commits different between the source and target branches

==== Shapes Editor
* Introduced a new policy for managing who can create a Shapes Graph Record
* Improved user experience when a user's access is limited within the editor
* Adjusted the defaults set when creating new Shapes Graph Records such that managing, deleting, and modifying the master branch are limited to the creator of the Record while viewing and general modification are enabled for everyone

==== Mapping Tool
* Adjusted the class select when creating a class mapping to dynamically pull the list from the source ontology and improve rendering time
* Adjusted process to map data into a Dataset to take into account the Dataset's policy

==== Discover
* Adjusted the Explore tool to take into account the Dataset's policy and display appropriate feedback to the user
* Improved user experience in the Query tool when the user is unauthorized to submit

== Release Notes for Mobi 1.21
Mobi 1.21 released on February 15, 2022. This release features the full release of the Ontology Visualization feature in the Ontology Editor, access control policies on datasets, a UI for defining the default IRI when creating new ontologies, and a brand new beta release of a Shapes Editor for Shapes Constraint Language (SHACL) files. It also includes various bug fixes and improvements.

=== What's New
* We've added a new beta module for editing SHACL Graphs called the <<shapes-editor-guide,Shapes Editor>>
* We've expanded the Ontology Visualization feature out of beta with a host of usability improvements
* We've added a section to customize application-wide settings to the Administration page

=== Detailed Notes

==== General Improvements and Fixes
* Upgraded AngularJS version to 1.8.2
* Upgraded Lodash version to 4.17.21

==== Catalog
* Fixed issue where a publisher was not set on the MASTER branch when a new record was created

==== Ontology Editor
* Updated the Ontology Visualization feature to enable customization of the graph by hiding and showing classes and ontologies in a collapsible side panel
* Updated merge workflow to prevent merges into the same branch as the source
* Added application setting to customize the default IRI for new ontologies
* Fixed issue where tabbing quickly after typing a character into the title field when creating a class would not update the IRI properly
* Fixed issue where circular subclass relationships were not properly represented in the class hierarchy
* Fixed issue where IRIs with an invalid extra "#" were accepted when editing an IRI

==== Merge Requests
* Updated merge workflow to prevent merges into the same branch as the source

==== Shapes Editor
* Introduced brand new beta module for editing SHACL shapes graphs with full versioning support. Behaves like the Ontology Editor with commits, branches, and tags to facilitate collaborative development. See <<shapes-editor-guide,Shapes Editor (BETA)>> for more details

==== Mapping Tool
* Improved formatting of JSON-LD preview

==== Datasets
* Introduced default access policies for Dataset Records. Default access only allows the creator to delete and manage record metadata

==== Administration
* Added a new section for managing Application Settings (see <<Application Settings>>)

== Release Notes for Mobi 1.20
Mobi 1.20 released on October 11, 2021. This release features a beta for Ontology Visualization in the Ontology Editor, updated `dct:modified` dates on Records, Record filtering by keyword in the Catalog, UPDATE query CLI support, and an extension to the Settings framework to support application wide settings. It also includes updates to policy handling, such as the filtering Records based on the user's ability to view the Record. Additionally, this release includes SPARQL query endpoint compliance, a REST interface for ETL, Basic Authentication on REST endpoints, Reflexive/Irreflexive property support, and various bug fixes and improvements.

=== What's New
* We've added a new beta feature for Ontology Visualization in the Ontology Editor
* We've added Record filtering by keywords in the Catalog
* We've introduced filtering Records based on the user's ability to view the Record

WARNING: `Query System Repo` policy will be reset to support updated SPARQL compliant endpoints.

=== Detailed Notes

==== General Improvements and Fixes
* Removed deprecated OWLAPI Ontology Implementation bundle
* Added support for UPDATE queries to the `mobi:query` CLI command. Has the ability to perform a dry run of the query displaying what will change
* Created an experimental REST interface for automatically translating source files into RDF with an extracted ontology. Currently supports XML, JSON, and CSV files
* Added Basic Authentication support to REST endpoints
* Introduced POST support to SPARQL Query endpoint in order to be more aligned with the SPARQL query endpoint specification
* Extended Settings framework to add support for application wide system settings
* The User Management module in the frontend code have been converted from AngularJS to Angular
* Added a REST endpoint to retrieve a Provenance Activity by resource ID
* Fixed issue with system policies being evicted from the policy cache and updated API for easier loading of policies
* Fixed issue where dangling graphs would persist across backup/restores
* Fixed system policy to restrict permissions to do everything from anyone with the admin role to only the admin user
* Fixed issue with Swagger docs not displaying list parameters correctly

==== Catalog
* Added the ability to filter Records based on keywords on the Record
* Updated `dct:modified` date of Records based on committing to a branch, adding/removing branches, editing branch metadata, and editing Record metadata
* Fixed issue where the markdown editor help text would be cut off by side component

==== Ontology Editor
* Introduced a beta feature for Ontology Visualization that will render up to 500 classes as nodes in a network graph, using the subclass relationships and object properties as edges. Uses the source Ontology and its imports
* Added the source Ontology IRI when viewing an imported entity
* Added `owl:ReflexiveProperty` and `owl:IrreflexiveProperty` support to properties
* Introduced a notification to the user when Ontology state is updated on reopen of an Ontology
* Added the ability to see the full ontology title on hover when importing an Ontology on the server
* Updated query REST requests to stream results back to the frontend
* Fixed issue where failed imports did not truncate
* Fixed issue in the Search Tab where the warning message did not display for searches with more than 500 results
* Fixed issue when viewing an Entity's history in a large Ontology would cause server slowdowns
* Fixed issue where a long imported Ontology IRI would extend past the confirm modal on deletion
* Fixed issue where a long imported Ontology IRI would extend past modal on addition

==== Mapping Tool
* Fixed issue where Classes from uncommitted changes on MASTER of source Ontologies appeared in Class selector

==== Discover
* Updated the display of syntax error messages in the Query tab when submitting invalid SPARQL queries to be more human-readable

==== My Account
* Fixed issue where updated names wouldn't immediately reflect the change in the side panel

==== Administration
* Added handling for cleaning up User State when deleting a User

== Release Notes for Mobi 1.19
Mobi 1.19 released on May 7, 2021. This release includes improved performance for various actions within the Ontology editor, support for uploading compressed ontology files, and new features for an improved editing and viewing experience. It also features a new https://www.w3.org/TR/shacl/[SHACL] based framework for setting user preferences in the UI, fully interactive Swagger documentation for our extensive REST APIs, and numerous bug fixes and improvements.

=== What's New
* We've added new Swagger-based REST API documentation where API calls can be tested live
* We've introduced a new framework for configuring and generating web forms for user preferences powered by https://www.w3.org/TR/shacl/[SHACL]
* We've introduced performance improvements to the Ontology Editor to better support uploading large ontologies and viewing the change history of ontology entities

=== Detailed Notes

==== General Improvements and Fixes
* Encryption of sensitive information stored within service configuration files is now enabled by default
* Changes to the master password used for service configuration encryption can be changed without having to restart the server
* Swagger REST API documentation is available on every running server (see documentation <<Accessing Swagger REST API Documentation, here>>)
* Enabled an experimental command-line feature for automatically translating source files into RDF with an extracted ontology. Currently supports XML, JSON, and CSV files
* Added full Java and REST API framework for storing, updating, and retrieving preferences based on https://www.w3.org/TR/shacl/[SHACL shape] definitions (see documentation <<Preferences Framework, here>>)
* Downgraded the jsonld-java library to fix issue where subjects could not be defined as a type of themselves
* Fixed issue where tags in an ontology were not included when exporting the record via the `mobi:export-record` command
* Fixed issue where icons did not load when not connected to the internet
* Fixed issue where logs viewed via the Karaf console did not display the Java Class names

==== Catalog
* Added ability to copy the full IRI of a commit when clicking on the hash in the commit info overlay
* Fixed issue where a new record "Overview" value would not immediately display after saving
* Fixed issue where In Progress Commits were not deleted from the repository when a Record was deleted

==== Ontology Editor
* Changed calculation of differences on upload changes to deterministically skolemize blank nodes to provide a more accurate difference
* Improved the performance of the See History view for individual entities in an ontology
* Improved the performance of caching an retrieving ontology data
* All ontology file uploads are automatically compressed before sending to the server for improved network performance
* Changed wording of info messages to be more helpful
* Combined the endpoints for uploading ontology JSON-LD and an ontology file such that the data and record metadata are both provided as form data parameters
* Added new filter to hierarchies to remove deprecated entities (i.e. items annotated with `owl:deprecated`)
* Added ability to upload zipped (`.zip`) and gzipped (`.gzip`) ontology files
* Added ability to copy the full IRI of a commit when clicking on the hash in the commit info overlay
* Added support for rendering SKOS-XL literal form as entity names in hierarchies and relationship labels
* Added support for `owl:TransitiveProperty` and `owl:SymmetricProperty` in Property Characteristics block
* Added ability to change the type of individuals in an ontology even if they do not contain the `owl:NamedIndividual` type
* Added support for creating qualified restrictions on a class where the class is another restriction. An example in Manchester Syntax looks like this: `isConnectedTo exactly 1 (Fin or Fuselage or Wing)`
* Added display of syntax errors to the upload changes overlay
* Added prevention of trig upload which would cause unexpected behavior
* Fixed issue where the class hierarchy did not fully reset after a branch was created
* Fixed issue where uploading the same ontology as changes still created an In Progress Commit
* Fixed issue where uploading an ontology file with a non resolvable import threw an error
* Fixed issue where See History did not update when switching branches
* Fixed issue where a "IRI already exists" error would display for a split second when creating a new entity

==== Merge Requests
* Fixed issue where long ontology names caused the second step of creating a Merge Request to horizontally scroll

==== Mapping Tool
* Added ability to copy the full IRI of a commit when clicking on the hash in the commit info overlay
* Fixed issue where full mapping definition was not returned when downloading a mapping

==== Discover
* Fixed issue where blank nodes defined as known classes caused errors in the Explore tool when viewing the class list and list of instances

==== My Account
* New Preferences tab that will populate with User Preference https://www.w3.org/TR/shacl/[SHACL] definitions from the repository (see documentation <<Preferences, here>>)
* Confirm password input in Password tab was converted to a single field with the ability to unmask the value for verification

==== Administration
* Confirm password input in Reset Password overlay and Create User overlay was converted to a single field with the ability to unmask the value for verification

== Release Notes for Mobi 1.18
Mobi 1.18 released on November 3, 2020. This release includes improved performance when viewing the differences of a specific commit or between two commits. It also has a brand new SPARQL query editor that supports CONSTRUCT queries as well, expressive syntax error displays on ontology uploads, support for encrypting passwords stored in service configuration files, and updates to several underlying libraries between the backend and frontend.

=== What's New
* We've introduced performance improvements to the Ontology Editor, Merge Requests, and Catalog to support viewing extremely large collections of differences while also displaying the calculated name for each entity instead of the local name of the IRIs 
* We've introduced a new SPARQL query editor in the Discover module with a better query editing experience, resizable editor and results areas, and support for CONSTRUCT SPARQL queries
* We've added the ability to view syntax errors when an ontology upload fails
* We've added configurable encryption of sensitive information stored within service configuration files

=== Detailed Notes

==== General Improvements and Fixes
* Updated RDF4J version to 2.5.5
* New support for configuring a master encryption password used to protect plaintext property values stored within service configuration files
* The Login and Home modules in the frontend code have been converted from AngularJS to Angular
* Improved memory usage when iterating through large sets of RDF statements in the backend
* Fixed issue where users would see a "Problem Getting States" error when logging in
* Added security policy for Dataset creation.

==== Catalog
* Changed the display of commit differences to load incrementally and display the calculated names of each entity instead of the local name of the IRI

==== Ontology Editor
* Added support for `owl:versionInfo` and `owl:versionIRI`
* Added more intelligent identification of the RDF format of a file when uploading ontologies
* Added display of syntax errors to the ontology upload snackbar
* Changed the display of commit differences to load incrementally and display the calculated names of each entity instead of the local name of the IRI
* Improved performance of the Concepts hierarchy by reworking a filter used within the Annotation, Data Property, and Object Property sections
* Improved performance of the query to fetch entity names within the ontology leading to faster open times
* Fixed issue where the endpoint for fetching the list of branches had no default sort value
* Fixed issue where search text was not properly highlighting matches within the list of ontologies
* Fixed issue where modals for creating entities within an ontology accepted invalid characters at the beginning of the IRI
* Fixed issue where modals for editing an IRI accepted invalid characters
* Fixed issue where editing an `owl:subPropertyOf` axiom would cause Concept tab to lose identification of imported concepts
* Fixed issue where the text of the selected data or object property in the "Add Datatype Property Value" modal would extend past the edge of the modal
* Fixed issue where changing the language of a skos:prefLabel value on a Concept Scheme or Concept would cause an "Invalid JSON-LD" error

==== Merge Requests
* Changed the display of commit differences to load incrementally and display the calculated names of each entity instead of the local name of the IRI
* Fixed issue where ontology IRIs would extend past their cards in the first step of creating a merge request on Firefox

==== Mapping Tool
* Changed the display of commit differences to load incrementally
* Fixed issue where the selected property would not load when editing an existing property mapping

==== Discover
* Introduced new policy to control who can create Datasets within the system (available in the User Management module)

==== Discover
* Refactored Query submodule to re-skin http://yasgui.org/[YASGUI] for Mobi
* Introduced CONSTRUCT query support to both frontend Query editor and backend endpoints
* Changed JSON response for SELECT SPARQL queries to conform to the https://www.w3.org/TR/sparql11-results-json/[W3C specification]
* Introduced utility Java class to support converting SELECT SPARQL query results to JSON, CSV, and TSV

== Release Notes for Mobi 1.17
Mobi 1.17 released on August 5, 2020. This release includes major performance improvements, allowing the ontology editor to support much larger ontologies than it could before. It also has a new "Active Entity" filter in each of the ontology tabs that will optionally filter out imported entities from the hierarchy view, configurable token duration for account logins, a limit on the amount of data shown in the Preview Block of the Ontology Editor, and now defaults to using the Repository Implementation for the Ontology API.

=== What's New
* We've introduced performance improvements to the Ontology Editor to support extremely large ontologies with hundreds of thousands of entities as well increasing application response speed for various actions.
* We've introduced a new filter for the hierarchy in each of the ontology tabs that will optionally filter out imported entities from the hierarchy view
* We've added configurable token duration for account logins

=== Detailed Notes

==== General Improvements and Fixes
* Added scaffolding that includes new packages and files to help facilitate the switch from angularJS to angular
* Application now defaults to using the Repository Implementation for the Ontology API
* New support for configurable token duration for account logins
* Added a line in the config specifying the default port for Mobi.
* Fixed issue where the username of the logged in user was replaced with "..." if it was to long to fit in the navbar instead of truncating.

==== Ontology Editor
* New "Active Entity" filter in each of the ontology tabs that will optionally filter out imported entities from the hierarchy view
* Refactored the Ontology Editor to store only required data for rendering in the web application rather than the entire Ontology RDF
* New backend endpoint to retrieve full RDF for a specified entity along with it's transitively attached blank nodes
* Modified the behavior on click of an entity in the hierarchy so that it retrieves the entity RDF from the new GET entity endpoint.
* Modified the GET ontology-stuff endpoint to include a map of entity IRIs in the imports closure to the values of properties used in calculating the display name
* Removed the GET ontology calls from the frontend to improve performance, especially when opening large ontologies
* Modified the GET commit endpoint to only retrieve commit metadata instead of full list of differences
* Modified the GET differences endpoint to make the target commit ID optional
* Improved performance of opening an Ontology
* Improved performance of switching branches
* Improved performance of retrieving ontology data after a new commit
* Improved performance of uploading an Ontology
* Improved the Ontology Editor module to support extremely large ontologies with hundreds of thousands of entities
* Added a limit to the amount of data displayed in the Preview block to improve performance of large ontologies
* Fixed issue where the ontology upload modal would stop appearing if the user accidentally clicked off of the ontology upload modal
* Fixed issue where imported ontologies without an Ontology IRI defined showed up blank in the Imports block of the Project tab
* Fixed issue where a long title for an ontology would expand the row on the Ontology List page too far horizontally and push the page content to the right along with it
* Fixed issue where a modal would close if you clicked on something in the modal, held the click, and released outside of the modal
* Fixed issue where application would run out of memory when merging large ontologies with merge conflicts
* Fixed issue where incorrect blank nodes were generated from certain Manchester Syntax strings

==== Catalog

* Fixed issue where the graph in the Catalog Commit table overlapped with the Creator column

== Release Notes for Mobi 1.16

Mobi 1.16 released on October 7, 2019. This release includes a Webpack and Typescript frontend, a new implementation of the backend Ontology API, better SKOS and SKOS-XL vocabulary support, and various other performance improvements.

=== What's New

* We've introduced a completely new implementation of the backend Ontology API that utilizes a triplestore for caching and querying information.
* We've changed the build process and language of the frontend code from Gulp and JavaScript to Webpack and TypeScript.
* We are continuing to create a more consistent look-and-feel across the application. To that end, we've included several UI updates to various tools.

=== Detailed Notes

==== General Improvements and Fixes
* Switched certain backend services to OSGi DS annotations instead of deprecated BND annotations
* Switched backup/restore methods to copy and replace all configuration files except for server specific files
* Switched backend library for generated JSON from net.sf to Jackson for improved performance
* New support for milliseconds for all stored xsd:dateTime values
* New backend support for users external to Mobi
* New support for committing mapped data to an ontology using the `mobi:transform` command
* Refactored how tokens are generated and verified in the backend
* New policy for controlling who can run a SPARQL query against the system repository
* Fixed issue with thread allocation in OWL API Ontology API implementation.
* Fixed issue where passwords with special characters could not be saved.
* Fixed issue where usernames were case sensitive.
* Fixed issue where restoring an older version of Mobi overwrote the version of the deployed bundles on a clean start

==== Ontology Editor
* New implementation of the backend Ontology API that allows for the uploading and opening of .OBO ontologies
* New implementation of the backend Ontology API that uses a repository for caching and querying
* New backend endpoint for retrieving the list of ontology IRIs in the imports closure
* Improved performance of opening and switching branches of large ontologies
* Improved performance of displaying a commit's changes for large ontologies
* Improved performance of calculating conflicts between commits with a large number of changes
* Improved performance of the Changes when displaying a large number of changes
* Improved performance of uploading a large number of changes to an ontology
* Default the commit dropdown in the See History view to the latest commit
* New support for creating a branch when viewing a specific commit
* New support for displaying values of the SKOS-XL literalForm property as the display name for SKOS-XL Labels
* Reworked Concepts and Schemes tab to show all data and object properties
* Fixed issue where searches of large ontologies crashed the browser
* Fixed issue where imported concepts were not displayed underneath their parent concept schemes in the Schemes tab
* Fixed issue where a changed entity in a hierarchy would not update when a commit was made
* Fixed broken "go to" functionality in the Object Property section of the Individuals tab
* Fixed bug where JavaScript console errors appeared when closing an ontology with the new entity snackbar visible

==== Catalog

* Fixed issue where updating record metadata would remove all other entities within the Record's named graph (such as linked ontologies for Dataset Records)
* Fixed issue where commits would not display for a branch of a VersionedRDFRecord when switching which branch was open

==== Merge Requests

* New backend support for editing comments on a merge request

==== Datasets

* New backend support for querying specific named graphs within a dataset using a Dataset Repository Connection
* Fixed issue where a SPARQL query in the form of `CONSTRUCT WHERE {...}` against a Dataset would not be rewritten properly

==== Administration

* Fixed issue where the list of groups would not update after one was created
* Fixed issue where the table of members of a group would not update after removing a member

== Release Notes for Mobi 1.15

Mobi 1.15 released on March 28, 2019. This release includes a redesigned Catalog, new ontology editor usability features, and several performance and API improvements.

=== What's New

* We've completely reworked the Catalog to improve search and usability. We've added functionality for editing record metadata, including support for Markdown descriptions.
* We've implemented several new features in the ontology editor to improve user experience. Users can now filter hierarchies based on search terms and view the change history of individual entities. We've implemented "scroll-to" functionality for quickly navigating to deeply nested terms, and provide a more complete list of language tags when annotating strings.
* We've improved processing of large ontologies including better memory management and processing of complex hierarchies.
* We are continuing to create a more consistent look-and-feel across the application. To that end, we've included several UI updates to various tools.

=== Detailed Notes

==== General Improvements and Fixes
* Upgraded underlying RDF4J version to 2.4.3.
* Upgraded underlying AngularJS version to 1.7.7.
* Added support for SPARQL and HTTP backing repositories
* Added documentation on how to use IRIs with URL encoded symbols in Mobi CLI.
* Restructured web files to reduce nested directories and have a consistent naming scheme.
* Made improvements to frontend routing so redirects to the login page are more intuitive.
* Refactored the return structure of the users and groups REST endpoints to improve performance and correctly encode strings.
* Fixed issues with text overflow in several views.
* Fixed an issue where backups made with the Mobi CLI on Windows machines would not restore correctly on Unix or Linux machines.

==== Ontology Editor

* New support for filtering hierarchies based on search text. Matches any annotations used for calculating the display name along with the local name.
* New support for viewing entity change history. Displays the list of commits where an entity was changed and what the entity looked like at each change.
* New support for opening a newly created entity via a snackbar and auto scrolling to its location in the list.
* New support for auto scrolling to an entity in the list when clicking "Go To" from the search tab.
* New support for a much larger list of language tags when creating annotations. 
* In the Ontology API, refactored retrieval of hierarchical relationships to use the Ontology object rather than an in-memory repository.
* Refactored Ontology API to remove unused classes.
* Changed the processing of hierarchical relationships in the Ontology REST and frontend for faster processing.
* Fixed an issue where the list of entities in the search tab where not sorted.

==== Catalog

* New support for opening a record in its respective module from the catalog.
* New support for adding a Markdown description to records you have the permission to manage.
* New support for editing the title, description, and keywords of records you have the permission to manage.
* Developed new look and feel for the Catalog UI.

==== Merge Requests

* Updated UI components to be consistent with the rest of the application.
* Fixed an issue where Merge Requests were not properly deleted if they had reply comments.

==== Dataset Manager

* Fixed issue where invalid dataset IRIs spaces were accepted.

== Release Notes for Mobi 1.14

Mobi 1.14 released on January 18, 2019. This release includes several new features for ontology versioning, tools for creating better review and ingest workflows with merge requests and the mapping tool, and major performance improvements.

=== What's New

* We've developed new features for viewing older versions of an ontology in the ontology editor. You can now select commits from the Commits tab to open those versions in read-only mode. You can also tag any commit to create a human readable and persistent pointer to a particular commit to track multiple ontology versions.
* We've implemented several performance improvements across the application to improve user experience when uploading, opening, and editing large ontologies.
* We've added several new features to the Merge Request tool, including discussions, to help improve user experience for review workflows.
* In our previous release, we added capabilities for mapping data into ontologies. In this release we've improved this capability by adding features for de-duplicating committed data and for calculating differences between mapping results and existing data. These features should enable workflows for versioning externally managed ontologies and vocabularies.
* In order to ease the burden of upgrading Mobi to a new version, we've included Mobi command line tools for creating full system backups and restores. For instructions on upgrading from version 1.13 check out this https://inovexirad.atlassian.net/servicedesk/customer/kb/view/725581873[KB Article].
* We are continuing to create a more consistent look-and-feel across the application. To that end, we've included several UI updates to various tools.

=== Detailed Notes

==== General Improvements and Fixes

* Upgraded underlying RDF4J version to 2.4.1.
* Modified the default repository indexing strategy to include named graph indexing by default. This should increase performance considerably on larger repository sizes.
* Added support for automatically compressing all web service responses.
* Added support for full system backup and restore through the Mobi CLI.
* Added support to the ORM framework for removing values of a functional property for an ORM Object.
* Refreshed User Management modal UI design to be more consistent with the rest of the application.
* Fixed an issue causing performance degradation when committing large sets of data to Versioned RDF Records.

==== Ontology Editor

* New support for creating tags within an ontology. Tags are persistent identifiers for specific commits.
* New support for opening specific commits and tags. These commits and tags are opened in read-only mode.
* Added support for querying ontology data via web services and optionally including imported ontologies.
* Added support for editing the types of owl:NamedIndividuals.
* Added support for admins to bypass access control for ontology records.
* Refreshed the UI display for the Search and Changes tabs to be more consistent with the rest of the application.
* Added support for automatically updating the ontology list when a set of uploads completes.
* Reworked the ontology import selector to enable search and a better ontology selection experience.
* Fixed an issue where the ontology list was not properly loaded when filter queries were abnormally slow.
* Fixed an issue where ontology record was corrupted if the client connection was lost during upload.
* Fixed an issue preventing opening of an ontology that imports another ontology that has an identical ontology and version IRI.
* Fixed performance issues when rendering large entity hierarchies.
* Fixed an issue causing display of double scrollbars in some ontology editor panels.
* Fixed an issue where circular subclass relationships prevent ontology opening.
* Fixed an issue improperly displaying a success toast after closing access control management with no changes.
* Fixed an issue that improperly opened a modal when ontology upload is cancelled.

==== Merge Requests

* New support added for creating and deleting comments and replies in merge requests to facilitate discussions.
* Added support for editing open merge requests.
* Added support for removing the source branch upon merge.

==== Mapping Tool

* Added support for committing mapped ontology entities to a specific branch rather than only the master branch.
* Added support for removing data from the mapping results that already exists on the target branch during ontology mapping.
* Added support for calculating differences between mapping results and data on the target branch during ontology mapping.
* Refreshed modal UI design to be more consistent with the rest of the application.
* Reworked the ontology selector to enable search and a better ontology selection experience.
* Fixed an issue with improperly processing empty rows in a CSV file in certain situations.
* Fixed an issue causing filename to improperly display when changing file selection in the Mapping Tool.

==== Catalog

* Added better support for rendering branches in a Versioned RDF Record view.

==== Dataset Manager

* Reworked the ontology selector to enable search and a better ontology selection experience.

== Release Notes for Mobi 1.13

Mobi 1.13 released on October 10, 2018. This release includes a completely refreshed user experience, ontology access control, new tools for creating ontologies and vocabularies, and enhanced features for ontology review workflows.

=== What's New

* We've developed an entirely new look-and-feel for the Mobi application. This update includes a brand new Home Page and a redesigned Ontology Editor.
* We released the beginnings of our policy-based access control in 1.12 and have expanded that to all ontology records. You can now control which users and groups can create, read, modify, and delete ontologies.
* For those of you maintaining vocabularies in Excel files, you can now use the mapping tool to load those files into Mobi ontologies. Simply create a mapping based on SKOS or OWL and use the "Commit to Ontology" option.
* Merge requests are a great way to create ontology review workflows and we've added new features for assigning, editing, and accepting them.

=== Detailed Notes

==== General Improvements and Fixes

* Redesigned look and feel for the Mobi web application including new Home Page and Ontology Editor designs
* Refactored conflict checking to provide better support for a variety of merge scenarios
* Upgraded underlying Apache Karaf version to 4.2.0
* Developed a new extensible framework for managing catalog records including record type specific implementations for export, delete, and create
* Refactored file naming and storage strategy for Mobi Binary Store
* Refactored policy services to use the Mobi Binary Store for policy storage and retrieval
* Added support for managing access control for ontology records. Support includes user and group control for view, delete, record modification, and master branch modification.
* Added support for configuring default location for the Mobi Binary Store
* Added web service support for comparing differences between two commits on a Versioned RDF Record
* Added service support for sending email notifications
* Fixed an issue where passwords do not match error was not being properly cleared
* Fixed an issue where merging duplicate changes from two branches sometimes resulted in statements remaining that should have been deleted

==== Ontology Editor

* Properly implemented backend paging for the ontology list
* Redesigned entity creation in the ontology editor. Creation now happens through the editor button stack instead of within each individual tab.
* Prioritize rendering of english labels in hierarchy views
* Added support for horizontal scrolling in hierarchy views
* Added support for drag-and-drop upload of ontologies
* Added web service support for querying ontology versions with SPARQL
* Fixed an issue where adding and removing an import did not properly clean up the user's in-progress commit
* Fixed an issue with an incorrect error message when uploading an empty ontology
* Fixed an issue with commit table rendering of long user names
* Fixed an issue where uploading ontologies with missing entities on restrictions resulted in Error Entities being displayed
* Fixed an issue where anonymous ontologies did not properly show the commit history

==== Merge Requests

* Added support for assigning merge requests to users
* Added support for accepting merge requests
* Added support for resolving merge conflicts within a merge request. Request still available for review after conflict resolution.

==== Mapping Tool

* Added support for mapping the same property to multiple columns of a tabular file
* Added support for Annotation Properties in property mappings
* Added support for selecting datatypes in property mappings
* Added support for selecting languages in property mappings
* Added support for committing mapping results to an ontology record
* Fixed an issue when mapping ontology properties for blank cells

== Release Notes for Mobi 1.12

Mobi 1.12 released on May 18, 2018. This release includes new features for collaborating and reviewing changes to ontologies as well as a new policy-based security architecture.

=== General Improvements and Fixes

* Released new, extensible service layer for managing hierarchical record types within the Mobi Catalog.
* Updated underlying RDF4J version to 2.2.4
* Updated underlying OWLAPI version to 5.1.4
* Fixed an issue in being unable to delete a record that had no associated provenance data.
* Fixed an issue affecting evaluation order of commits within branching commit chains for Versioned RDF Records.
* Fixed an issue preventing Windows machines from running the Mobi CLI client.

=== Security

* Released new support for policy-based access control. New APIs and backend services support managing and evaluating security policies for controlling actions at all layers of the platform.
* Support added for controlling which users and groups can create ontologies.

=== Merge Requests

* Released new module for managing merge requests. Merge requests are long lived components that enable reviewing changes between branches of a record before performing a merge.

=== Ontology Editor

* Reworked behavior of ontology editor when making changes while behind the head of a branch. New notifications and seamless merging has been implemented to make this process more intuitive.
* Support added for viewing relevant commit list when merging two branches.
* Support added for saving state of in-progress merge actions when switching tabs.
* Fixed an issue where StackOverflowErrors were thrown when processing sufficiently deep class hierarchies.
* Fixed an issue where the ontology creation page did not retain state when switching between modules.
* Fixed an issue where exceptions during ontology upload still created a record.
* Fixed an issue where the owl:deprecated property was not properly being recognized as a boolean value.
* Fixed an issue where downloading an ontology while a mapping was being edited resulted in a page transition confirmation dialog.
* Fixed an issue with languages and datatypes not being properly displayed in ontology search results.
* Fixed an issue where failed ontology uploads were not being properly displayed in the ontology upload screen.
* Fixed an issue where ontology search results did not include matches for all literal types.
* Fixed an issue where the ontology commit table was showing the commit history for the entire branch even if the user was behind the head of that branch.
* Fixed an issue with improper overflow of text in the ontology imports panel.
* Fixed an issue allowing merge actions to be completed when a user has uncommitted changes.
* Fixed an issue where re-uploading an ontology improperly indicates success after initially indicating failure.

=== Mapping Tool

* Fixed an issue where local ontology changes affected mappings being edited at the same time.

=== Discover Module

* Fixed an issue where navigating away from editing an instance would automatically save changes instead of cancelling.

== Release Notes for Mobi 1.11

Mobi 1.11 released on January 24, 2017. This release features improvements to ontology version control, data management and exploration, and numerous bug fixes and performance improvements across the platform.

=== General Improvements and Fixes

* Support added for configuring Repositories based on standard SPARQL endpoints.
* Support added for copying values from RDF preview blocks.
* Support added for using minified web resources in production builds.
* Added link to the Mobi Help Center in the application help menu.
* Fixed an issue causing an intermittent "Application not found" error after the server has been unexpectedly shutdown.
* Fixed an issue causing slow load time for the Activity Log.
* Fixed an issue where triples were not properly being tracked if the same triple was added and removed in the same commit.

=== Ontology Editor

* Improved branch merging process. Merges are now initiated through a button on the button stack. Commit changes are aggregated and shown beneath the branch selector. Finally, the conflicts view has been updated to improve readability of entity change conflicts. These improvements make it easier to review changes between branches before merging.
* Support added for tighter integration between the Individuals tab and Concepts tab when developing SKOS vocabularies.
* Support added for uploading multiple ontologies at once through file browser or drag-and-drop.
* Improved web-app performance when managing large lists of entities in an ontology.
* Support added for using inferences when suggesting relationships and creating new Concepts in the Concepts Tab.
* Fixed an issue that caused an intermittent gray screen in the ontology editor after logging out and back in.
* Fixed an issue causing incorrect overflow of long imported ontology labels.
* Fixed an issue where skos:narrower is not properly nesting Concepts in the Concepts tab.
* Fixed an issue where Top Concepts are not properly nested beneath Concept Schemes.
* Fixed an issue with dropdown item selection when entities are defined within an ontology and its imports.
* Fixed an issue where the property creation dialog box was cut-off on low resolution displays.
* Fixed an issue causing an error when a user's ontology editor state suggested opening an ontology to a previously deleted branch.
* Fixed an issue where the ontology cache was not properly updated after deleting the source branch during a merge.
* Fixed an issue where Concepts could be related to themselves.
* Fixed an issue allowing users to add duplicate values for the same property to an ontology entity.
* Fixed an issue with class folders being added to the individuals tab incorrectly when creating subclass axioms.

=== Dataset Manager

* Support added for uploading RDF data files to a dataset through the Dataset Manager UI.

=== Discover Module

* Support added for using inferences when suggesting link targets while editing instances in the Explore tool.

== Release Notes for Mobi 1.10

Mobi 1.10 released on November 27, 2017. This release features improvements to vocabulary editing, new instance management tools, and numerous bug fixes across the platform.

=== General Improvements and Fixes

* Incorporated new automated web testing framework for testing web UI components.
* Added many new backend services and features to support future distributed catalog capabilities.
* Added many new backend services and features to support future ETL workflow capabilities.
* Fixed an issue with ORM API causing ConcurrentModificationExceptions when editing functional properties with more than value assigned

=== Ontology Editor

* Completed a major overhaul of the vocabulary editor. The vocabulary editor features have now been rolled into the ontology editor and dynamically become available upon declaration or import of SKOS classes. Additionally, various display improvements have been made for the Schemes and Concepts views.
* Fixed an issue causing dropdowns with hundreds of items or more to become unresponsive. Dropdowns with large numbers of items now show a subset of items and allow searching.
* Fixed a variety of issues causing performance problems when loading large ontologies
* Fixed a variety of issues causing performance problems when loading ontologies with large import closures
* Fixed an issue where imported classes retrieved via REST endpoint contained some incorrect values
* Fixed an issue with the preview block not updating when switching ontology tabs
* Fixed an issue with the preview block not correctly grouping triples by subject
* Fixed an issue with missing ontology properties from the edit ontology properties block
* Fixed an issue causing display problems when switching between web modules
* Fixed an issue with poor display of long branch names in the branch select box
* Fixed an issue with inconsistent use of inferred ontology entities

=== Mapping Tool

* Mapping components (class and property mappings) now have associated titles so that they are more easily identified.
* Support added for creating multiple class mappings of the same type. This allows mapping different properties to the same class type.

=== Dataset Manager

* Added missing form label for ontologies list
* Fixed an issue where linked ontologies were not correctly retrieved
* Fixed an issue causing performance problems when importing large data files into a dataset

=== Discover Module

* Support added for searching with property paths in the Search tool
* Support added for creating new instances of classes from the class page in the Explore tool
* Support added for showing labels of linked instances in the Explore tool
* Support added for showing labels of available instances for linking in the Explore tool
* Support added for deleting instances in the Explore tool
* Fixed an issue when customizing IRIs of new instances in the Explore tool
* Fixed an issue where editing an instance property did not correctly add datatypes in the Explore tool

== Release Notes for Mobi 1.9

Mobi 1.9 released on October 20, 2017. This release features new provenance, search, and visualization features as well as numerous bug fixes across the platform.

=== General Improvements and Fixes

* New provenance features collect information about catalog record creation and deletion events, and provide an Activity Log in the web UI. This data collection joins existing capabilities tracking record modification to provide a detailed picture about how resources within Mobi are being created, used, and destroyed. Future improvements will provide more detailed visualization tools and collection capabilities to track all resources within Mobi at a detailed level.
* Updated the project source code to reflect the rebranding from MatOnto to Mobi
* New backend service capabilities added to manage ETL workflows. Future improvements will bring UI tools for creating and managing workflows that include ingest from relational database, XML, and directory-based data sources.
* New backend service capabilities added for managing files and file systems
* Fixed an issue where dates were not properly persisted with the xsd:dateTime datatype

=== Ontology Editor

* Improvements made in how the ontology editor handles blank node data within the browser
* Fixed an issue impeding the loading of ontologies with a large number of direct or indirect imports
* Fixed an issue that caused the new ontology tab to disappear intermittently
* Fixed an issue where commit change labels were not being properly rendered in some cases
* Fixed an issue where users were not always able to pull the latest changes from the server when behind the HEAD of a branch
* Fixed an issue where ontology entities were not being properly expanded and collapsed in entity trees
* Fixed an issue where new Concepts were not being dynamically nested based on SKOS relationships
* Fixed an issue where editing Concepts in the Scheme tab provided the wrong list of relationships
* Fixed an issue where deleted Concepts could not be made again
* Fixed an issue where searching on a newly created vocabulary resulted in many missing entities
* Fixed an issue where clicking a Concept link in the ontology editor did not correctly navigate to the Individuals tab

=== Mapping Tool

* Fixed an issue where updating the ontology version was not properly saved to the mapping record
* Fixed an issue where mappings could not be run from the edit page unless changes were made
* Fixed an issue where dropdown boxes were not correctly populated after modifying the mapping ontology

=== Dataset Manager

* Fixed an issue where pagination in dataset creation overlay did not work properly
* Fixed an issue with incorrect info messages on the Dataset Manager UI module
* Fixed an issue where selected ontologies were improperly displayed when editing a dataset

=== Catalog

* Fixed an issue where catalog sorting options contained duplicate values
* Fixed an issue where the catalog module broke when a selected record was deleted

=== Analytic Module

* New module added to support development of analytics and visualizations in the Mobi web application. This initial release includes features for developing dynamic tables based on user-managed ontologies. Future improvements will bring charting, dashboard, and reporting capabilities.

=== Federation Services

* Renamed services and data to reflect new federation naming scheme
* Fixed an issue where modifying service configurations did not immediately reconfigure federation services
* Fixed an issue where platform services were not able to start correctly if MAC address could not be determined

=== CLI

* Support added for submitting SPARQL queries via the Mobi command-line client

== Release Notes for Mobi 1.8

Mobi 1.8 released on August 27, 2017. This release features the official rebranding of the MatOnto platform as Mobi. Key features include improved support for OWL Restrictions, new support for local ontology imports, new features for instance data editing and creation, and a new "Search" tool within the Discover Module.

=== General Improvements and Fixes

* New support added for importing and exporting data from the Mobi console. Support includes importing data into an existing dataset and exporting dataset data and catalog records.
* Support added to the Mobi console for exporting named graphs from a repository
* Fixed several build errors related to running unit tests in Windows environments
* Fixed an issue where commit fragments were not being properly removed when a Versioned RDF Record was deleted

=== Ontology Editor

* Improved support for rendering OWL Restrictions including owl:oneOf and cardinalities
* Support added for owl:inverseOf and owl:AsymmetricProperty
* Support added for adding ontology imports from the local server
* Support added for identifying indirect ontology imports in the imports closure
* Support added for identifying missing ontology imports
* Support added for creating a commit by uploading a modified version of an ontology (enabling external ontology modification)
* Support added for applying owl:deprecated to ontology classes
* Refactored the vocabulary editor to split schemes and concepts into their own editor tabs
* Fixed an issue where SKOS relationships were not available within the vocabulary editor
* Fixed an issue where entity usages were not being properly displayed within the ontology editor
* Fixed an issue where IRI existence validation was improperly reporting errors
* Fixed an issue where especially long RDF lists within an ontology would cause stack overflow errors

=== Mapping Tool

* Support added for properly respecting owl:deprecated on ontology classes
* Support added for versioning mapping records
* Support added for processing formulas within Excel files
* Fixed an issue where the mapping name was unmodifiable within the mapping editor

=== Discover Module

* New "Search" tool added to the Discover Module. "Search" tool supports keyword, type, and data property search within a dataset.
* Support added to the "Explore" tool for viewing, editing, and creating instance data
* Support added to the "Explore" tool for applying properties to existing data through the use of reification
* Support added to the "Explore" tool for respecting required properties when creating and editing instance data

=== Datasets

* Support added for editing datasets from the Datasets Module

=== Federation Services

* New features added for creating federations of Mobi nodes as a first step toward enabling distributed collaboration

=== API Updates

* Improved versioning services to properly version quads in addition to triples
* Support added to properly edit blank node resources by skolemizing blank nodes between the triplestore and the web application
* Fixed an issue for properly handling null values in DatasetConnection.remove(s, p, o, c)

=== Known Issues

* In the Vocabulary Editor, adding hierarchical relationships (e.g. broader and narrower) to concepts does not properly nest them in the concept tree until the vocabulary is reopened.
* There is a typo in the `etc/branding-ssh.properties` that causes the Karaf client to hang. This will be fixed in release 1.9.

== Release Notes for MatOnto 1.7

MatOnto 1.7 released on June 5, 2017. This release includes many bug fixes and performance improvements for the ontology editor and mapping tool as well as a new Discover Module for exploring datasets.

=== General Improvements and Fixes

* Fixed an issue where retrieving users with email addresses in the User Management tool caused an Internal Server Error

=== Discover Module

* Replaced the existing SPARQL Editor Module with the new Discover Module
* Added "Explore" tool to the Discover Module to enable quick exploration of datasets. This new tool will show the user what types of data are stored in the dataset and provide data samples. Future updates to the tool will allow users to explore and modify instance properties, create new instances, and delete existing instances.
* Fixed an issue where comments were not allowed in SPARQL queries against datasets

=== Ontology Editor

* Improved parsing of entity local names with acronyms used for display values (e.g. http://example.com/ontology#ABCEntity -> "ABC Entity")
* Support added for directly adding a subClassOf or subPropertyOf axiom when creating a new class or property
* Fixed an issue allowing users to create multiple ontology entities with the same IRI
* Fixed an issue where some commit data was not removed when deleting an ontology
* Fixed an issue where the individuals tree was not updated correctly when the ontology class tree changed
* Fixed an issue where a user could not assign a ConceptScheme when creating a new Concept

=== Mapping Tool

* Support added for applying datatypes to literals based on the selected ontology properties
* Support added for using basic rdfs and dcterms properties in a mapping
* Support added for mapping multiple properties to the same source data column
* Fixed an issue where modifying an ontology that was also being used in an active mapping broke the mapping ontology selector
* Fixed an issue where the Mapping Tool was not properly including ontology updates when selecting the latest ontology version

=== API Updates

* Refactored public Catalog API to include path validation when performing operations such as creating commits and merging branches
* Significant performance improvements when retrieving commit data from the Catalog REST endpoints. Dramatically reduces load times for large ontologies.
* Support added for creating commits from external data. This capability will enable future support for applying commits from files and merging records.
* Various improvements to memory management when opening ontologies. Dramatically reduces memory usage when opening large ontologies.

=== Known Issues

* In the Vocabulary Editor, SKOS relationship properties are missing from the property selector when using subclasses of skos:Concept. This issue will be fixed in Release 1.8.
* Intermittent build errors occur in the Catalog REST bundle due to some shared resources. This issue will be fixed in Release 1.8.
* The Mapping improperly includes InProgressCommit data when loading ontology properties and classes. This issue will be fixed in Release 1.8.
* SPARQL queries against datasets that include SPARQL keywords as variable names cause a parsing exception. This issue will be fixed in a future release.
* Classes that subclass each other should result in an equivalence relationship. This is not properly rendered in the Ontology Editor and produces errors. This issue will be fixed in a future release.
* The Mapping Tool does not correctly handle mapping object properties with no range. The tool allows you to select the object property, but produces an error when trying to determine the target class type. This issue will be fixed in a future release.
* The Mapping Tool does not correctly save mappings that have had their name changed. This issue will be fixed in Release 1.8.

== Release Notes for MatOnto 1.6

MatOnto 1.6 released on May 8, 2017. This release includes many bug fixes and performance improvements for the ontology editor as well as various improvements to the mapping tool and user management page.

=== General Improvements and Fixes

* Google groups link added to help menu
* User management user list now displays full name if available
* Access to user management page restricted to admins only
* Support added to list a user's groups in the profile page
* Fixed an issue where targeted spinner would lock up the application in several places
* Fixed an issue where admin tags were not displayed correctly in the user list of the user management page

=== Ontology Editor

* Support added for a click-to-copy feature for ontology entity IRIs
* Support added to render complex class expressions and restrictions using Manchester Syntax in Axioms panel
* Support added to render complex class expressions and restrictions using Manchester Syntax in Search panel
* Support added to include imported entities in class, property, and individual list
* Support added to roll-up large number of entity usages into a link to increase performance
* Support added to render individuals of subtypes of skos:Concept in the concept hierarchy of the vocabulary editor
* Support added to implement virtual scrolling on all entity lists, dramatically improving performance for large ontologies
* Support added to render individuals as a tree based on their class hierarchy
* Support added to implement ontology caching, dramatically improving performance when loading and editing large ontologies
* Support added to immediately render icons associated with ranges of properties in the property hierarchy and overview tab
* Fixed an issue where deleting an ontology did not delete the underlying revision data
* Fixed an issue where creating and deleting classes sometimes resulted in incomplete class data remaining in the ontology
* Fixed an issue where import statements were not correctly displayed in the changes tab
* Fixed an issue where adding and deleting multiple imports did not correctly delete the specified import
* Fixed an issue where deleting individuals did not always remove them from the individuals list
* Fixed an issue where axiom values were not displayed properly in dropdowns
* Fixed an issue where the String datatype was being removed from an individual's data property when committing
* Fixed an issue where modification badges would not be removed after performing a commit
* Fixed an issue where the project tab would not update on branch change

=== Mapping Tool

* Support added for editing full IRI in IRI templates
* Support added to ignore property mappings for empty cells when mapping in delimited and excel files
* Support added to ignore class mappings for empty rows when mapping in delimited and excel files
* Support added to trim white space from values inserted into IRI templates
* Support added to show a preview of mapped data in the property mappings list
* Fixed an issue where the edit and delete buttons for property mappings would not work in Firefox
* Fixed an issue where the user could not create a new class mapping when editing a previously created mapping resource
* Fixed an issue where previewing mapping results intermittently did not display correctly
* Fixed an issue where using an ontology with the same class defined in the ontology and one of its imports resulted in an empty dropdown when adding a class mapping
* Fixed an issue where page leave confirmation message was displayed when downloading a mapped data

=== Datasets

* Support added to associate datasets with ontologies that describe the data within them

== Release Notes for MatOnto 1.5

MatOnto 1.5 released on April 4, 2017. This release contains the first features for MatOnto datasets and many improvements to the Ontology Editor user experience.

=== Datasets

A new feature in 1.5, MatOnto Datasets provide collections of RDF graphs that can be managed and queried independently of other data stored within MatOnto repositories.

* Datasets consist of a collection of RDF graphs that act as default named graphs or named graphs per the SPARQL 1.1 recommendation for https://www.w3.org/TR/sparql11-query/#rdfDataset[RDF Datasets].
* Java and REST services are now available for creating, managing, and querying datasets. The services ensure all operations on the Dataset are isolated to that specific set of RDF graphs.
* A new UI module provides capabilities for creating and managing datasets.

=== Ontology Editor

* Support added for displaying and editing language tags on string literals.
* Support added for displaying and selecting if a property is functional.
* Support added for importing ontologies from a URL. When adding an import, the editor will confirm the URL is resolvable and reload the ontology with the imported entities.
* The *Commits* tab now renders a commit history chain with links to view the commit changes.
* Added support for loading spinners over specific UI components when waiting on asynchronous calls to load data. This can be seen in the entity usages block.
* All entity hierarchy trees are now sorted alphabetically.
* When rendering labels for entities in hierarchy trees or detail blocks, a "pretty-print" label is displayed using the `rdfs:label`, `dc:title`, or the local name of the IRI in that order.
* The editor now supports passive saving. When an ontology entity is modified, the ontology is automatically saved.
* Modified entities are now highlighted using a modification badge and bold formatting.
* Support added for creating custom Annotation Properties.
* Each entity now displays a list of its `rdf:type`.

=== Mapping Tool

* Integration with MatOnto Datasets provides the capability to upload transformed data to a Dataset.
* Removed the idea of a "Base Class" from the mapping configuration. You now select from a list of classes in an order to create class mappings.

=== SPARQL Query Editor

* Integration with MatOnto Datasets provides the capability to limit a query operation to a particular Dataset.
* Malformed queries now properly display a message describing the parsing error.
* New feature allows user to download the results of a SPARQL tuple query in CSV, TSV, or Excel format.

=== General Improvements and Fixes

* User management tool now allows an admin to reset a user's password.

=== Known Issues

* Double-clicking an entity in the Ontology Editor search results wil not remove the loading spinner. Reload the browser tab to clear this issue.
